MAX_PAGINATION = 5000

PAGINATION_ALL = {
    'nbperpage': MAX_PAGINATION,
    'pagenum': 1,
}

SEARCH_TYPE_CLIENTS = 'Client'
SEARCH_TYPE_DOCUMENTS = 'Document'
SEARCH_TYPE_PRODUCTS = 'Catalogue'

PRODUCT_TYPE_ITEM = 'item'
PRODUCT_TYPE_SERVICE = 'service'

CLIENT_TYPE_CORPORATION = 'corporation'
CLIENT_TYPE_PERSON = 'person'

DOCUMENT_TYPE_CREDIT_NOTE = 'creditnote'
DOCUMENT_TYPE_INVOICE = 'invoice'
DOCUMENT_TYPE_PROFORMA = 'proforma'

INVOICE_STATUS_DRAFT = 'draft'
INVOICE_STATUS_DUE = 'due'
INVOICE_STATUS_PARTIALLY_PAID = 'payinprogress'
INVOICE_STATUS_PAID = 'paid'
INVOICE_STATUS_LATE = 'late'
INVOICE_STATUS_CANCELLED = 'cancelled'
VALID_INVOICE_STATUSES = (
    INVOICE_STATUS_DRAFT,
    INVOICE_STATUS_DUE,
    INVOICE_STATUS_PARTIALLY_PAID,
    INVOICE_STATUS_PAID,
    INVOICE_STATUS_LATE,
    INVOICE_STATUS_CANCELLED,
)

PAYMENT_MODE_BOR = 'bor'
PAYMENT_MODE_CARD = 'cb'
PAYMENT_MODE_CASH = 'cash'
PAYMENT_MODE_CHECK = 'check'
PAYMENT_MODE_CREDIT = 'credit'
PAYMENT_MODE_DIRECT_DEBIT = 'pick'
PAYMENT_MODE_LCR = 'lcr'
PAYMENT_MODE_TIP = 'tip'
PAYMENT_MODE_TRANSFER = 'transfer'

DISCOUNT_UNIT_AMOUNT = 'amount'
DISCOUNT_UNIT_PERCENT = 'percent'
