MAX_PAGINATION = 5000

PAGINATION_ALL = {
    'nbperpage': MAX_PAGINATION,
    'pagenum': 1,
}

SEARCH_TYPE_CLIENTS = 'Client'
SEARCH_TYPE_DOCUMENTS = 'Document'
SEARCH_TYPE_PRODUCTS = 'Catalogue'
SEARCH_TYPE_PEOPLES = 'Peoples'

PRODUCT_TYPE_ITEM = 'item'
PRODUCT_TYPE_SERVICE = 'service'

CLIENT_TYPE_CORPORATION = 'corporation'
CLIENT_TYPE_PERSON = 'person'

DOCUMENT_TYPE_CREDIT_NOTE = 'creditnote'
DOCUMENT_TYPE_INVOICE = 'invoice'
DOCUMENT_TYPE_PROFORMA = 'proforma'

# See https://api.sellsy.fr/documentation/principles#docssteps
DOCUMENT_STATUS_DRAFT = 'draft'
DOCUMENT_STATUS_DUE = 'due'
DOCUMENT_STATUS_PARTIALLY_PAID = 'payinprogress'
DOCUMENT_STATUS_PAID = 'paid'
DOCUMENT_STATUS_LATE = 'late'
DOCUMENT_STATUS_INVOICED = 'invoiced'  # proforma only!
DOCUMENT_STATUS_CANCELLED = 'cancelled'
DOCUMENT_STATUS_ACCEPTED = 'accepted'
VALID_DOCUMENT_STATUSES = (
    DOCUMENT_STATUS_DRAFT,
    DOCUMENT_STATUS_DUE,
    DOCUMENT_STATUS_PARTIALLY_PAID,
    DOCUMENT_STATUS_PAID,
    DOCUMENT_STATUS_LATE,
    DOCUMENT_STATUS_INVOICED,
    DOCUMENT_STATUS_CANCELLED,
    DOCUMENT_STATUS_ACCEPTED,
)

PAYMENT_MODE_BOR = 'bor'
PAYMENT_MODE_CARD = 'cb'
PAYMENT_MODE_CASH = 'cash'
PAYMENT_MODE_CHECK = 'check'
PAYMENT_MODE_CREDIT = 'credit'
PAYMENT_MODE_DIRECT_DEBIT = 'pick'
PAYMENT_MODE_LCR = 'lcr'
PAYMENT_MODE_TIP = 'tip'
PAYMENT_MODE_TRANSFER = 'transfer'

DISCOUNT_UNIT_AMOUNT = 'amount'
DISCOUNT_UNIT_PERCENT = 'percent'
